// <auto-generated />
using HRApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HRApplication.Migrations.Position
{
    [DbContext(typeof(PositionContext))]
    partial class PositionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRApplication.Models.Application", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicantID");

                    b.Property<string>("CoverLetterPath");

                    b.Property<string>("Experience");

                    b.Property<string>("PositionID");

                    b.Property<string>("ResumePath");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("HRApplication.Models.Position", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
